@startuml dashboard_apps
:Kewilayahan Dashboard: as KewilayahanDashboard
:Dashboard Monitoring Proyek Infrastruktur: as DashboardMonitoringProyekInfrastruktur
:Executive Dashboard: as ExecutiveDashboard
(Performance tracking) as (Performancetracking)
(Real-time reporting) as (Real-timereporting)
(Data visualization) as (Datavisualization)
(Decision making support) as (Decisionmakingsupport)
KewilayahanDashboard --> (Performancetracking)
KewilayahanDashboard --> (Real-timereporting)
KewilayahanDashboard --> (Datavisualization)
KewilayahanDashboard --> (Decisionmakingsupport)
DashboardMonitoringProyekInfrastruktur --> (Performancetracking)
DashboardMonitoringProyekInfrastruktur --> (Real-timereporting)
DashboardMonitoringProyekInfrastruktur --> (Datavisualization)
DashboardMonitoringProyekInfrastruktur --> (Decisionmakingsupport)
ExecutiveDashboard --> (Performancetracking)
ExecutiveDashboard --> (Real-timereporting)
ExecutiveDashboard --> (Datavisualization)
ExecutiveDashboard --> (Decisionmakingsupport)
@enduml
