@startuml data_management_apps
:Sistem Repository Prov Jabar: as SistemRepositoryProvJabar
:Aplikasi Data Tidak Terstruktur: as AplikasiDataTidakTerstruktur
:Login Executive Dashboard: as LoginExecutiveDashboard
:Aplikasi Servicedesk: as AplikasiServicedesk
:Web Open Data Jawa Barat: as WebOpenDataJawaBarat
:Login Data Pembangunan Jawa Barat: as LoginDataPembangunanJawaBarat
:Jabar Open Data (Landing Page Portal Data Jabar): as JabarOpenData(LandingPagePortalDataJabar)
(Data entry) as (Dataentry)
(Data analysis) as (Dataanalysis)
(Data visualization) as (Datavisualization)
(Data reporting) as (Datareporting)
(Data cleaning) as (Datacleaning)
(Data integration) as (Dataintegration)
(Input Data) as (InputData)
(Read Data) as (ReadData)
(Update Data) as (UpdateData)
(Delete Data) as (DeleteData)
SistemRepositoryProvJabar --> (Dataentry)
SistemRepositoryProvJabar --> (Dataanalysis)
SistemRepositoryProvJabar --> (Datavisualization)
SistemRepositoryProvJabar --> (Datareporting)
SistemRepositoryProvJabar --> (Datacleaning)
SistemRepositoryProvJabar --> (Dataintegration)
SistemRepositoryProvJabar --> (InputData)
SistemRepositoryProvJabar --> (ReadData)
SistemRepositoryProvJabar --> (UpdateData)
SistemRepositoryProvJabar --> (DeleteData)
AplikasiDataTidakTerstruktur --> (Dataentry)
AplikasiDataTidakTerstruktur --> (Dataanalysis)
AplikasiDataTidakTerstruktur --> (Datavisualization)
AplikasiDataTidakTerstruktur --> (Datareporting)
AplikasiDataTidakTerstruktur --> (Datacleaning)
AplikasiDataTidakTerstruktur --> (Dataintegration)
AplikasiDataTidakTerstruktur --> (InputData)
AplikasiDataTidakTerstruktur --> (ReadData)
AplikasiDataTidakTerstruktur --> (UpdateData)
AplikasiDataTidakTerstruktur --> (DeleteData)
LoginExecutiveDashboard --> (Dataentry)
LoginExecutiveDashboard --> (Dataanalysis)
LoginExecutiveDashboard --> (Datavisualization)
LoginExecutiveDashboard --> (Datareporting)
LoginExecutiveDashboard --> (Datacleaning)
LoginExecutiveDashboard --> (Dataintegration)
LoginExecutiveDashboard --> (InputData)
LoginExecutiveDashboard --> (ReadData)
LoginExecutiveDashboard --> (UpdateData)
LoginExecutiveDashboard --> (DeleteData)
AplikasiServicedesk --> (Dataentry)
AplikasiServicedesk --> (Dataanalysis)
AplikasiServicedesk --> (Datavisualization)
AplikasiServicedesk --> (Datareporting)
AplikasiServicedesk --> (Datacleaning)
AplikasiServicedesk --> (Dataintegration)
AplikasiServicedesk --> (InputData)
AplikasiServicedesk --> (ReadData)
AplikasiServicedesk --> (UpdateData)
AplikasiServicedesk --> (DeleteData)
WebOpenDataJawaBarat --> (Dataentry)
WebOpenDataJawaBarat --> (Dataanalysis)
WebOpenDataJawaBarat --> (Datavisualization)
WebOpenDataJawaBarat --> (Datareporting)
WebOpenDataJawaBarat --> (Datacleaning)
WebOpenDataJawaBarat --> (Dataintegration)
WebOpenDataJawaBarat --> (InputData)
WebOpenDataJawaBarat --> (ReadData)
WebOpenDataJawaBarat --> (UpdateData)
WebOpenDataJawaBarat --> (DeleteData)
LoginDataPembangunanJawaBarat --> (Dataentry)
LoginDataPembangunanJawaBarat --> (Dataanalysis)
LoginDataPembangunanJawaBarat --> (Datavisualization)
LoginDataPembangunanJawaBarat --> (Datareporting)
LoginDataPembangunanJawaBarat --> (Datacleaning)
LoginDataPembangunanJawaBarat --> (Dataintegration)
LoginDataPembangunanJawaBarat --> (InputData)
LoginDataPembangunanJawaBarat --> (ReadData)
LoginDataPembangunanJawaBarat --> (UpdateData)
LoginDataPembangunanJawaBarat --> (DeleteData)
JabarOpenData(LandingPagePortalDataJabar) --> (Dataentry)
JabarOpenData(LandingPagePortalDataJabar) --> (Dataanalysis)
JabarOpenData(LandingPagePortalDataJabar) --> (Datavisualization)
JabarOpenData(LandingPagePortalDataJabar) --> (Datareporting)
JabarOpenData(LandingPagePortalDataJabar) --> (Datacleaning)
JabarOpenData(LandingPagePortalDataJabar) --> (Dataintegration)
JabarOpenData(LandingPagePortalDataJabar) --> (InputData)
JabarOpenData(LandingPagePortalDataJabar) --> (ReadData)
JabarOpenData(LandingPagePortalDataJabar) --> (UpdateData)
JabarOpenData(LandingPagePortalDataJabar) --> (DeleteData)
@enduml
