@startuml event_related_apps
:Web site Event Jabar Prov: as WebsiteEventJabarProv
(Event planning) as (Eventplanning)
(Event promotion) as (Eventpromotion)
(Ticket sales) as (Ticketsales)
(Event scheduling) as (Eventscheduling)
WebsiteEventJabarProv --> (Eventplanning)
WebsiteEventJabarProv --> (Eventpromotion)
WebsiteEventJabarProv --> (Ticketsales)
WebsiteEventJabarProv --> (Eventscheduling)
@enduml
