@startuml logistics_apps
:Logistik Alat Kesehatan: as LogistikAlatKesehatan
(Inventory management) as (Inventorymanagement)
(Supply chain management) as (Supplychainmanagement)
(Delivery tracking) as (Deliverytracking)
(Order processing) as (Orderprocessing)
LogistikAlatKesehatan --> (Inventorymanagement)
LogistikAlatKesehatan --> (Supplychainmanagement)
LogistikAlatKesehatan --> (Deliverytracking)
LogistikAlatKesehatan --> (Orderprocessing)
@enduml
