@startuml mapping_apps
:GIS Aset Tanah dan Bangunan: as GISAsetTanahdanBangunan
:Web Satu Peta Jawa Barat: as WebSatuPetaJawaBarat
(Geospatial analysis) as (Geospatialanalysis)
(Asset tracking) as (Assettracking)
(Route planning) as (Routeplanning)
(Location-based service) as (Location-basedservice)
GISAsetTanahdanBangunan --> (Geospatialanalysis)
GISAsetTanahdanBangunan --> (Assettracking)
GISAsetTanahdanBangunan --> (Routeplanning)
GISAsetTanahdanBangunan --> (Location-basedservice)
WebSatuPetaJawaBarat --> (Geospatialanalysis)
WebSatuPetaJawaBarat --> (Assettracking)
WebSatuPetaJawaBarat --> (Routeplanning)
WebSatuPetaJawaBarat --> (Location-basedservice)
@enduml
