@startuml media_related_apps
:web site KPID: as websiteKPID
(Media content management) as (Mediacontentmanagement)
(Media content distribution) as (Mediacontentdistribution)
(Media content creation) as (Mediacontentcreation)
(Media content analysis) as (Mediacontentanalysis)
websiteKPID --> (Mediacontentmanagement)
websiteKPID --> (Mediacontentdistribution)
websiteKPID --> (Mediacontentcreation)
websiteKPID --> (Mediacontentanalysis)
@enduml
