@startuml storage_apps
:Drive Jabarprov: as DriveJabarprov
(File storage) as (Filestorage)
(File sharing) as (Filesharing)
(File backup) as (Filebackup)
(File synchronization) as (Filesynchronization)
DriveJabarprov --> (Filestorage)
DriveJabarprov --> (Filesharing)
DriveJabarprov --> (Filebackup)
DriveJabarprov --> (Filesynchronization)
@enduml
